Kong/kong-portal-templates

default/pages/unauthenticated/login.hbs
This PR adds a check for `document.getElementById('username')` before trying to modify its value.
=> fix(login): add check for username id to prevent js error

themes/default/partials/unauthenticated/assets/base/base-css.hbs, themes/default/partials/unauthenticated/assets/layout/sidebar-css.hbs
Relies on https://github.com/Kong/kong-portal/pull/307
=> fix(swagger-ui): fix resize issue, improve operation colors

themes/default-ie11/partials/spec/sidebar-list.hbs, themes/default-ie11/partials/unauthenticated/assets/layout/sidebar-css.hbs, themes/default/partials/spec/sidebar-list.hbs, themes/default/partials/unauthenticated/assets/layout/sidebar-css.hbs
=> feat(sidebar): add HTTP methods to links

bin/sync.js
- Allows to use `./` when declaring theme directory
- Properly checks boolean values for `PUSH,PULL,DELETE_ALL,WATCH,EMOJI` variables
=> fix(sync): variable boolean check, and theme name fix

themes/default-ie11/pages/unauthenticated/register.hbs, themes/default-ie11/partials/unauthenticated/registration-form-vue.hbs
This PR updates the ie11 theme to also support developer-meta-fields
=> Fix/ie11 developer meta fields DX-548

bin/sync.js
No more issues with sync script on crappy postgress instances
Adds ERROR_WAIT defaults to 2 seconds 
Also adds lots of catches
=> fix(sync): fixes 500 error

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md
[x] Add contributor license agreement via cli-assistant
[ ] Document requirement for signing the agreement
[x] Document code of conduct (a separate document), and link requirement to read.
[x] Document preferred the coding style
[x] Document process for submitting pull requests
[x] Document process for submitting an issue
=> upgrade in contributing documentations (#52 resolved)

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md
Before start with KONG please read the CONTRIBUTING.md guidelines to learn where and on which 
channel you can search for the help and can ask genral question
Also read the CODE_OF_CONDUCT.md to get the idea about code format and policies of KONG
SUMMARY_GOES_HERE
1.
2.
3.
4.
1.
2.
3.
4.
1.
2.
3.
4.
=> chore(*) upgrade in contributing documentations

workspaces/default/themes/light-theme/assets/styles/site.css
=> fix(style): secondary button

workspaces/default/themes/light-theme/assets/styles/site.css, workspaces/default/themes/light-theme/layouts/system/settings.html, workspaces/default/themes/light-theme/partials/header.html
=> feat(dropdown): fix auth dropdown

workspaces/default/themes/light-theme/partials/header.html
=> chore(header) remove guides link

workspaces/default/themes/light-theme/partials/header.html
=> feat(safe access): update helper functions to getters where needed

workspaces/default/themes/light-theme/layouts/catalog.html, workspaces/default/themes/light-theme/partials/service-catalog/list.html
=> fix(catalog) update catalog to take tag filter element

workspaces/default/content/account/invalidate-verification.txt, workspaces/default/content/account/resend-verification.txt, workspaces/default/content/account/verify.txt, workspaces/default/content/dashboard.txt, workspaces/default/content/login.txt, workspaces/default/content/logout.txt, workspaces/default/content/register.txt, workspaces/default/content/reset-password.txt, workspaces/default/content/settings.txt, workspaces/default/content/verify-account.txt
=> feat(private tags): add private headmatter tags to non public files

workspaces/default/specs/petstore.yaml
=> fix(petstore) add base tag for petstore spec

workspaces/default/specs/httpbin.json, workspaces/default/themes/light-theme/partials/service-catalog/list.html
https://konghq.atlassian.net/secure/RapidBoard.jspa?rapidView=29&modal=detail&selectedIssue=EBB-254
=> fix(catalog): add empty state for catalog

workspaces/default/content/about/index.txt
https://konghq.atlassian.net/browse/EBB-255
=> fix(content): EBB-255 remove cruft

workspaces/default/themes/light-theme/assets/styles/site.css, workspaces/default/themes/light-theme/partials/header.html
=> fix(header): update header to correctly center logo regardless of size

workspaces/default/cli.conf.yaml
This PR updates the cli conf with the new values used by the CLI
=> feat(cli) update cli conf with new values

workspaces/default/emails/invite.txt
Removes quotes from invite subject
=> fix(email) remove trailing quotes from invite email subject

workspaces/default/themes/base/assets/styles/swagger-ui-kong-theme.css
=> fix(code-highlighting): re-introduce code highlighting to code snippets

workspaces/default/themes/base/layouts/system/spec-renderer.html
=> fix(spec-renderer): update delimiter syntax to improve parse compatibility

workspaces/default/cli.conf.yaml
=> fix(conf) remove kong admin token

workspaces/default/content/oauth2-redirect.txt, workspaces/default/themes/base/layouts/system/oauth2-redirect.html, workspaces/default/themes/base/layouts/system/spec-renderer.html
Chery pick from dev-master for oauth2 issue.
=> fix(swagger): add redirect for oauth2 (#123)

workspaces/default/themes/base/layouts/_app.html, workspaces/default/themes/base/layouts/system/applications.html, workspaces/default/themes/base/layouts/system/create-app.html, workspaces/default/themes/base/layouts/system/dashboard.html, workspaces/default/themes/base/layouts/system/edit-app.html, workspaces/default/themes/base/layouts/system/invalidate-verification.html, workspaces/default/themes/base/layouts/system/resend-verification.html, workspaces/default/themes/base/layouts/system/reset-password.html, workspaces/default/themes/base/layouts/system/settings.html, workspaces/default/themes/base/layouts/system/spec-renderer.html, workspaces/default/themes/base/layouts/system/verify-account.html, workspaces/default/themes/base/layouts/system/view-app.html
=> fix(js): consolidate js version

workspaces/default/themes/base/assets/js/kong/kong.auth.js
=> fix(auth) do not read redirectTo from query param

workspaces/default/themes/base/assets/styles/swagger-ui-kong-theme.css
=> fix(swagger): register button always on right side

workspaces/default/themes/base/assets/js/kong/kong.auth.js
=> fix(auth): do not read redirectTo from query param

workspaces/default/themes/base/assets/js/kong/kong.auth.js
=> fix(auth): do not read redirectTo from query param (#132)

Jenkinsfile
=> feat(jenkins) initial jenkinsfile

Jenkinsfile, bootstrap.mk
=> chore(ci-cd) add Makefile

bootstrap.mk
Update kong-portal-tools branch for ci
=> chore(ci) change kong-portal-tools branch to master

.github/PULL_REQUEST_TEMPLATE.md
Hello,
This PR will fix : 
- 1 typo in `.github/PULL_REQUEST_TEMPLATE.md`
Cheers! :robot:
=> Fix typo in .github/PULL_REQUEST_TEMPLATE.md

Jenkinsfile
- adds Portal Files stage to generate portal files on merge to dev-master
- switches credential to PORTAL_GITHUB_USER
- no long run e2e on master
=> chore(ci-cd) update ci to generate templates on merge to dev-master

workspaces/default/themes/base/theme.conf.yaml
Make theme.conf.yaml more consistent
Always use quotes for descriptions
Description always comes after value
Fix a few typos
=> Make theme.conf.yaml more consistent
